# Generated by Django 3.1 on 2020-08-14 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obavestenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('sadrzaj', models.TextField()),
                ('datum_objave', models.DateTimeField(default=django.utils.timezone.now)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('azuriran', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('nacrt', 'NACRT'), ('objavljen', 'Objavljen')], default='objavljen', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postavljena_obavestenja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-datum_objave',),
            },
        ),
    ]
