# Generated by Django 3.1 on 2020-08-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obavestenje',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='datum_objave'),
        ),
    ]
