# Generated by Django 3.1 on 2020-08-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200815_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funkcija', models.CharField(max_length=250)),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=250)),
                ('telefon', models.CharField(max_length=50)),
            ],
        ),
    ]
