# Generated by Django 3.1 on 2020-08-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_kontakt'),
    ]

    operations = [
        migrations.AddField(
            model_name='obavestenje',
            name='dokument',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
